FROM resin/rpi-raspbian:jessie

MAINTAINER Jere Virta

RUN apt-get update && apt-get install -yq wget nano lsb-release curl apt-utils debian-keyring && \
    echo "deb http://debmon.org/debmon debmon-jessie main" >>/etc/apt/sources.list && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY content/ /
COPY start.sh /
RUN chmod +x /start.sh

ENV INITSYSTEM on

RUN echo "$MASTER_IP $MASTER_HOST" >>/etc/hosts

RUN echo "Welcome to Icinga2"

CMD "/start.sh"
